# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


jobs:
- job: Unit_Test

  steps:
  - script: python test/Calculation_Test.py

- job: S3_Upload
  dependsOn: Unit_Test
  condition: succeeded()
  steps:
  - task: S3Upload@1
    inputs:
      awsCredentials: 'Name_of_service_connection'
      regionName: 'eu-west-1'
      bucketName: 'XXX'
      sourceFolder: 'src/'
      globExpressions: '*'

  - task: Docker@2
    displayName: Build docker image
    inputs:
      command: build
      dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
      buildContext: '$(System.DefaultWorkingDirectory)'
      repository: $(AWS_ECR_MAGE_URI)

  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'XXX'
      regionName: $(AWS_REGION)
      imageSource: 'imagename'
      sourceImageName: $(AWS_ECR_MAGE_URI)
      sourceImageTag: $(Build.BuildId)
      pushTag: $(Build.BuildId)
      repositoryName: $(AWS_ECR_REPOSITORY_NAME)
